
[[constraint]]
  name = "github.com/form3tech-oss/alienvault"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.10"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gotest.tools"
  version = "2.3.0"

[prune]
  go-tests = true
  unused-packages = true
